DROP TABLE IF EXISTS KoeNayttelyTulos CASCADE;
DROP TABLE IF EXISTS Omistajasuhde CASCADE;
DROP TABLE IF EXISTS Sukulaissuhde CASCADE;

DROP TABLE IF EXISTS Koira CASCADE;

DROP TABLE IF EXISTS KoeNayttely CASCADE;
DROP TABLE IF EXISTS Kasvattaja CASCADE;
DROP TABLE IF EXISTS Omistaja CASCADE;
DROP TABLE IF EXISTS Rotu CASCADE;

DROP TABLE IF EXISTS Kayttaja CASCADE;